global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ulpf-m6'

scrape_configs:
  - job_name: 'm6-api'
    static_configs:
      - targets: ['m6-api:8000']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']
    honor_labels: true
